Lots of fixes and improvements (#7)
commit 83f6c7b618c6deb404915fba06876c211d15b2ac
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Sun Mar 1 17:07:33 2026 +0000

    Prettify output

commit 46f3186c805b0460211dcb02182f51752bcb82a7
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Sun Mar 1 16:01:28 2026 +0000

    Tidy greps

commit b15b13e2958c9163b3cbb640d7a15bb259d501e0
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Sun Mar 1 16:01:09 2026 +0000

    Tidy names of scripts

commit 522d4238c4ecb2470de621c871584327e6c53688
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Sun Mar 1 15:48:56 2026 +0000

    Some fixes for root user

commit c81a507afa9183cbccc5ff063c98c968d8ae931d
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Fri Feb 27 18:12:17 2026 +0000

    Sort aliases

commit b044576c9760fb741cdbe28e10de6ba38dc37641
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Fri Feb 27 18:09:57 2026 +0000

    Rearrange how scripts are called from each other

commit 6ac45d67f54d7cf2c28e3a4167e80498fa6a34a3
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Tue Feb 24 09:15:32 2026 +0000

    Add pretty feedback functions

commit 25e4a6ab17d42790f07854d55beadc32dbd69e40
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Tue Feb 24 08:57:12 2026 +0000

    Add support for wincrypt-sshagent again

commit 1783a182894a98c787488b6f02bf21813d0c0ff5
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Mon Feb 23 16:10:18 2026 +0000

    Improvements to setup scripts

commit 6a852cc07d9d5dd16a7e51e05753f9f9a07423ce
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Mon Feb 23 13:05:16 2026 +0000

    Add IS Apps proxying to ssh config

commit ff250a7009651d7121c44c459caf2971e135cff0
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Mon Feb 23 10:05:48 2026 +0000

    Update to work with wsltools

commit 1a32fb5f4811a534908548a96701fb5dc9a141d9
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 09:08:14 2026 +0000

    Remove stub

commit 21cebaa9cb3e3f54609ac23ea9e0a6fd4f159208
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 08:58:42 2026 +0000

    WSL clone moved to separate repo

commit 005912af7b8187857d3243406aa89ac0b04ad93b
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 08:56:12 2026 +0000

    Remove wincrypt-sshagent

commit 2905d8a1ec8e38d2239e0422c25a3494b926da47
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 08:55:40 2026 +0000

    Rearrange ssh config files

commit 55359b240899678b43105364fa984fa605d5d0d6
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 08:54:20 2026 +0000

    Rename ssh configs

commit 4962d4846ee3dbc6fb9f0a7d30c0497f1ca617ef
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Thu Feb 19 08:32:14 2026 +0000

    Change bashrc file names

commit 297199077ff30998c8b72939a7f0383a6665a8e9
Author: Hannah Morrison <139557138+hbmorrison@users.noreply.github.com>
Date:   Wed Feb 18 16:52:42 2026 +0000

    Break out bashrc into multiple scripts

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -7,13 +7,50 @@ then
   source /etc/os-release
 fi
 
+# Pretty feedback.
+
+GOTO_COLUMN="\\033[72G"
+RED='\033[00;31m'
+GREEN='\033[00;32m'
+CLEAR='\033[00m'
+
+notice () {
+  echo -n "${1^}... "
+}
+notice_yes () {
+  echo -e "${GOTO_COLUMN}${GREEN}Yes${CLEAR}"
+}
+notice_no () {
+  echo -e "${GOTO_COLUMN}${RED}No${CLEAR}"
+}
+notice_ok () {
+  echo -e "${GOTO_COLUMN}ok"
+}
+pass () {
+  echo -e "${GOTO_COLUMN}${GREEN}Done${CLEAR}"
+}
+fail () {
+  echo -e "${GOTO_COLUMN}${RED}FAILED${CLEAR}"
+  if [ ! -z ${1:+z} ]
+  then
+    echo -e "${RED}Error:${CLEAR} ${1}"
+    exit 1
+  fi
+}
+usage () {
+  if [ ! -z ${1:+z} ]
+  then
+    echo -e "${RED}Usage:${CLEAR} setup" "$@"
+    exit 1
+  fi
+}
+
 # Locate the base directory of the repository.
 
 THIS_SCRIPT=$(readlink -f $0)
 BIN_DIR=$(dirname $THIS_SCRIPT)
 BASE_DIR=$(dirname $BIN_DIR)
 ETC_DIR="${BASE_DIR}/etc"
-SETUP_SCRIPT=$(basename $0)
 LOCAL_BIN="${HOME}/.local/bin"
 
 # Check that symlink is set up.
@@ -32,28 +69,28 @@ ln -s $BIN_DIR/setup $LOCAL_BIN/setup
 # Work out whether to run commands using sudo.
 
 SUDO=sudo
-
-if [ `id -u` -eq 0 ]
+if [ $(id -u) -eq 0 ]
 then
   SUDO=""
 fi
 
-# Setup the user shell by default.
+# Get the name of the setup script from the command line.
 
-SUB_SCRIPT=""
-
+SCRIPT=""
 if [ ! -z ${1:+z} ]
 then
-  SUB_SCRIPT=$1
+  SCRIPT=$1
   shift
 fi
 
-# Work out the name of the setup script.
+# Work out the path to the setup script.
 
-SUB_SCRIPT_FILE="${BIN_DIR}/setup_${SUB_SCRIPT}.sh"
-
-if [ ! -f $SUB_SCRIPT_FILE ]
+SCRIPT_FILE="${BIN_DIR}/setup_${SCRIPT}.sh"
+if [ ! -f $SCRIPT_FILE ]
 then
+
+  # Print a usage message listing all available setup scripts.
+
   AVAILABLE_SCRIPTS="("
   for FILE in $BIN_DIR/setup_*.sh
   do
@@ -61,10 +98,9 @@ then
     AVAILABLE_SCRIPTS+="${NAME}|"
   done
   ARGS=$(echo $AVAILABLE_SCRIPTS | sed 's/|$/)/')
-  echo "Usage: ${SETUP_SCRIPT} ${ARGS}"
-  exit 1
+  usage "${ARGS}"
 fi
 
 # Run the setup script.
 
-source ${SUB_SCRIPT_FILE} $*
+source ${SCRIPT_FILE} $*
