Improve usage message

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -15,12 +15,15 @@ case $(/bin/cat /proc/version 2>/dev/null) in
   *microsoft-standard-WSL2*) OS="wsl";;
 esac
 
-# Locate the base directory of the repository.
+# Locate the base directory of the repository and sub directories.
 
 THIS_SCRIPT=$(readlink -f $0)
 BASE_DIR=$(dirname $THIS_SCRIPT)
 ETC_DIR="${BASE_DIR}/etc"
 SCRIPT_DIR="${BASE_DIR}/etc/setup"
+
+# Common directories.
+
 LOCAL_DIR="${HOME}/.local"
 LOCAL_BIN="${LOCAL_DIR}/bin"
 
@@ -33,7 +36,7 @@ YELLOW='\033[00;33m'
 BLUE='\033[00;36m'
 CLEAR='\033[00m'
 
-# Function that runs setup scripts.
+# Run a script.
 
 setup () {
   local script="${1}"
@@ -59,8 +62,8 @@ notice () { echo -en " - ${1^} " 1>&2; }
 # Non-fatal feedback is sent to stderr.
 
 pass () { echo -e "${GOTO_COLUMN}${GREEN}Done${CLEAR}" 1>&2; }
-fail () { echo -e "${GOTO_COLUMN}${YELLOW}Failed${CLEAR}" 1>&2; return 1; }
 yes () { echo -e "${GOTO_COLUMN}${GREEN}Yes${CLEAR}" 1>&2; }
+fail () { echo -e "${GOTO_COLUMN}${YELLOW}Failed${CLEAR}" 1>&2; return 1; }
 no () { echo -e "${GOTO_COLUMN}${YELLOW}No${CLEAR}" 1>&2; return 1; }
 
 # Fatal feedback that ends the script immediately.
@@ -105,12 +108,12 @@ else
   }
 fi
 
-# Check that symlink is set up.
+# Create a symlink to the setup script.
 
 [ -d $LOCAL_BIN ] || mkdir -p $LOCAL_BIN &>/dev/null
 ln -fs $BASE_DIR/setup $LOCAL_BIN/setup &>/dev/null
 
-# Get the name of the setup script from the command line.
+# Get the name of the script to run from the command line.
 
 SCRIPT=""
 if [ ! -z ${1:+z} ]
@@ -119,7 +122,7 @@ then
   shift
 fi
 
-# Work out the path to the setup script.
+# Work out the path to the script.
 
 SCRIPT_FILE="${SCRIPT_DIR}/${SCRIPT}.sh"
 if [ ! -f $SCRIPT_FILE ]
@@ -127,15 +130,15 @@ then
 
   # Print a usage message listing all available setup scripts.
 
-  AVAILABLE_SCRIPTS="<"
+  declare -a AVAILABLE_SCRIPTS
   for FILE in "${SCRIPT_DIR}/"*
   do
     NAME=$(basename -s .sh $FILE)
-    AVAILABLE_SCRIPTS+="${NAME}|"
+    [ -d "${FILE}" ] || AVAILABLE_SCRIPTS+=( $(basename -s .sh $FILE) )
   done
-  echo -e "${YELLOW}Usage:${CLEAR} setup ${AVAILABLE_SCRIPTS/%|/>}" 1>&2
+  echo -e "${YELLOW}Usage:${CLEAR} setup <$(IFS="|"; echo "${AVAILABLE_SCRIPTS[*]}")>" >&2
 fi
 
-# Run the setup script.
+# Run the script.
 
 setup "${SCRIPT}"
