Tidy things up

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -1,10 +1,5 @@
 #!/bin/bash
 
-# Windows directories in WSL.
-
-USER_PROFILE="/mnt/c/Users/${USER}"
-APPDATA_LOCAL="${USER_PROFILE}/AppData/Local"
-
 # Source OS release variables.
 
 if [ -f /etc/os-release ]
@@ -29,9 +24,60 @@ SCRIPT_DIR="${BASE_DIR}/etc/setup"
 LOCAL_DIR="${HOME}/.local"
 LOCAL_BIN="${LOCAL_DIR}/bin"
 
-# Pretty feedback notices.
+# Windows directories in WSL.
 
-source "${ETC_DIR}/notice.env"
+USER_PROFILE="/mnt/c/Users/${USER}"
+APPDATA_LOCAL="${USER_PROFILE}/AppData/Local"
+
+# Pretty feedback.
+
+GOTO_COLUMN="\\033[74G"
+RED='\033[00;31m'
+GREEN='\033[00;32m'
+YELLOW='\033[00;33m'
+CLEAR='\033[00m'
+
+notice () { echo -en "${1^} " 1>&2; }
+pass () { echo -e "${GOTO_COLUMN}${GREEN}Ok${CLEAR}" 1>&2; }
+fail () { echo -e "${GOTO_COLUMN}${YELLOW}Failed${CLEAR}" 1>&2; }
+
+fatal () {
+  echo -e "${GOTO_COLUMN}${RED}Failed${CLEAR}" 1>&2;
+  [ $# -eq 0 ] && exit 1
+  echo -e "${RED}Error:${CLEAR} $@" 1>&2
+  exit 1
+}
+
+usage () {
+  [ ! -z ${1:+z} ] && echo -e "${YELLOW}Usage:${CLEAR} setup ${SCRIPT}" "$@" 1>&2
+  exit 1
+}
+
+# Work out whether to run commands using sudo.
+
+SUDO=sudo
+if [ $(id -u) -eq 0 ]
+then
+  SUDO=""
+  setup_needs_sudo () {
+    notice "checking that user is root"
+    respond_yes
+  }
+else
+  setup_needs_sudo () {
+    notice "checking that user has sudo access"
+    if [ ! -z ${SUDO} ]
+    then
+      if ! sudo -n /bin/true 2>/dev/null && respond_yes
+      then
+        respond_no
+        sudo -v
+        notice "checking sudo access again"
+        sudo -n /bin/true 2>/dev/null && respond_yes || fatal "no sudo access"
+      fi
+    fi
+  }
+fi
 
 # Check that symlink is set up.
 
@@ -46,33 +92,13 @@ then
 fi
 ln -s $BASE_DIR/setup $LOCAL_BIN/setup
 
-# Work out whether to run commands using sudo.
+# Get the name of a profile or return the default profile.
 
-SUDO=sudo
-if [ $(id -u) -eq 0 ]
-then
-  SUDO=""
-  setup_needs_sudo () {
-    checking "that sudo credentials are valid"
-    respond_yes
-  }
-else
-  setup_needs_sudo () {
-    checking "that sudo credentials are valid"
-    if [ ! -z ${SUDO} ]
-    then
-      if sudo -n /bin/true 2>/dev/null
-      then
-        respond_yes
-      else
-        respond_no
-        sudo -v
-        checking "sudo credentials again"
-        sudo -n /bin/true 2>/dev/null && respond_yes || fatal "could not authenticate with sudo"
-      fi
-    fi
-  }
-fi
+get_profile () {
+  [ ! -z ${1:+z} ] && echo "${1}" && return
+  [ -z ${SETUP_PROFILE:+z} ] && fatal "SETUP_PROFILE not defined"
+  echo "${SETUP_PROFILE}"
+}
 
 # Get the name of the setup script from the command line.
 
